version: "3"

services:
  db:
    image: mysql:8.4
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      interval: 1m30s
      timeout: 30s
      retries: 5
      start_period: 30s
    environment:
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_DATABASE=stock_db
    ports:
      - 3306:3306
    container_name: mysql_stock

  app:
    build: .
    container_name: stock_service
    depends_on:
      db:
        condition: service_healthy
    environment:
      DATABASE_URL: mysql://root:root@db:3306/stock_db?schema=public
      PORT_APP: 9001
    expose:
      - 9001:9001
